### ISSUE TITLE
Github Action 으로 CI/CD 개발 with K8S

### ISSUE THREAD

**Issue by SeJonJ** [chatforyou-io/ChatForYou.io-back#19]
# Github Action 으로 CI/CD 개발 with K8S

## 목적
효율적인 CI/CD 환경 구축: GitHub Actions와 Kubernetes를 활용하여 애플리케이션 배포와 테스트를 자동화를 통해 피드백 주기를 단축하여 빠른 문제 해결과 지속적인 개선

## 목표
1. CI/CD 파이프라인 설계 및 구현:
- GitHub Actions를 활용하여 코드 푸시, PR, 병합 시 자동으로 빌드, 테스트, 배포가 이루어지는 파이프라인을 구축한다.
2. Kubernetes 기반 배포 자동화:
Kubernetes 클러스터에 새로운 애플리케이션 버전을 자동으로 배포하며, 롤링 업데이트와 같은 전략을 통해 다운타임 없는 배포를 실현한다(무중단 배포)
3. 보안 강화를 위한 워크플로우:
- GitHub Secrets 및 Kubernetes Secret 관리 기능을 활용하여 인증 정보와 민감한 데이터를 안전하게 관리한다.

**Comment by SeJonJ** [comment]
docker-image.yml 작성 후 빌드 및 k8s 배포 확인 완료
- 추가 테스트 후 작업 내용 공유 예정입니다.

**Comment by SeJonJ** [comment]
관련 정보 : https://gist.github.com/alo9507/1d1538d3767d856162209cbca25a81a4

**Comment by SeJonJ** [comment]
github action 을 활용한 CI/CD 개발 및 테스트 완료 후 내용 공유드립니다

- yml 변경이 필요합니다.
- 아래 내용의 secrets 에 해당하는 내용은 카톡으로 전달드리겠습니다!
- 아래 4번의 docker repo 로그인은 현재는 주석처리
->  가능한 빠른 시일 내 추가예정입니다. 추가 및 변경 후 다시 공유 드리겠습니다. 

```text
name: Docker CI/CD

on:
  push:
    branches: [ "master"]
#  pull_request:
#    branches: [ "master" ]

jobs:
  deploy:
    name: Build And Deploy K8S
    environment: chatforyou-back-env # 사용하는 깃허브 환경 이름에 맞춰 변경 필요
    runs-on: ubuntu-latest
    env:
     ## secrets 내용은 카톡으로 공유 예정 ##
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      IMAGE_REPO: ${{ secrets.IMAGE_REPO }}
      K8S_NAMESPACE: chatforyou-io # Kubernetes 네임스페이스(고정값)
      DEPLOYMENT_NAME: chatforyou-io # Deployment 이름(고정값)

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Kubeconfig 설정
      - name: Configure Kubeconfig
        run: |
          mkdir -p ${HOME}/.kube
          echo "${KUBE_CONFIG}" | base64 --decode > ${HOME}/.kube/config
          export KUBECONFIG=${HOME}/.kube/config

      # 3. TIMESTAMP 생성 (한국 시간으로)
      - name: Generate TIMESTAMP in KST
        id: timestamp
        run: |
          export TZ=Asia/Seoul
          echo "TIMESTAMP=$(date -d "${{ github.event.head_commit.timestamp }}" '+%Y%m%d%H%M%S')" >> $GITHUB_ENV

      #      # 4. Docker 로그인
      #      - name: Login to Docker Registry
      #        run: |
      #          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY_URL }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # 5. Docker 이미지 빌드 및 태그
      - name: Build Docker Image
        run: |
          docker build --file Dockerfile -t $IMAGE_REPO:${{ env.TIMESTAMP }} .

      # 6. Docker 이미지 푸시
      - name: Push Docker Image
        run: |
          docker push $IMAGE_REPO:${{ env.TIMESTAMP }}

      # 7. Kubernetes 배포
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/$DEPLOYMENT_NAME \
            chatforyou-container=$IMAGE_REPO:${{ env.TIMESTAMP }} \
            -n $K8S_NAMESPACE
          kubectl rollout status deployment/$DEPLOYMENT_NAME -n $K8S_NAMESPACE
```

**Comment by SeJonJ** [comment]
@junotb 
github packages 에 docker image push 및 k8s 에 배포하는 작업 진행중에 있습니다.
결과적으로 성공! 했고 현재 테스트 진행중입니다. 따라서 위에있는 docker.yml 사용하지마시구 잠시만 기다려주시면 감사하겠습니다!

**Comment by SeJonJ** [comment]
# 1. github action CI/CD 용 최종 yml
``````yaml
name: Docker CI/CD

on:
  push:
    branches: [ "master", "infra/cicd-test" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  deploy:
    name: Build And Deploy K8S
    environment: chatforyou-back-env # 환경 지정
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      K8S_NAMESPACE: chatforyou-io # Kubernetes 네임스페이스
      DEPLOYMENT_NAME: chatforyou-io # Deployment 이름

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Kubeconfig 설정
      - name: Configure Kubeconfig
        run: |
          mkdir -p ${HOME}/.kube
          echo "${KUBE_CONFIG}" | base64 --decode > ${HOME}/.kube/config
          export KUBECONFIG=${HOME}/.kube/config

      # 3. TIMESTAMP 생성 (한국 시간으로) && IMAGE_URI 로 이미지명:태크명 공통화
      # IMAGE_URI = chatforyou-io/chatforyou-io-backend:시간
      - name: Generate TIMESTAMP in KST
        id: timestamp
        run: |
          export TZ=Asia/Seoul
          TIMESTAMP=$(date '+%Y%m%d%H%M%S')
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
          # 이미지명 예시 : chatforyou-io-backend
          echo "IMAGE_URI=ghcr.io/${{ github.repository_owner }}/{이미지명}:$TIMESTAMP" >> $GITHUB_ENV

      # 5. Docker 이미지 빌드 및 태그
      - name: Build Docker Image
        run: |
          docker build --file Dockerfile -t $IMAGE_URI .

      # 6. Docker 이미지 푸시 (GitHub Container Registry)
      - name: Push Docker Image to GitHub Packages
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push $IMAGE_URI

      # 7. Kubernetes 배포
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/$DEPLOYMENT_NAME \
            chatforyou-container=$IMAGE_URI \
            -n $K8S_NAMESPACE
          kubectl rollout status deployment/$DEPLOYMENT_NAME -n $K8S_NAMESPACE

````````````````````



# 2. package 설정 변경
- package > 생성된 package 내 repository
- repository 에서 아래 사진과 같이 설정해야합니다.
-> 미설정 시 ci/cd 시 권한 에러 발생

![Image](https://github.com/user-attachments/assets/0270add2-63cc-4d4c-9111-b2dfc150273a)
